#
# Copyright Greg Haskins All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
FROM _NS_/fabric-basejvm:_TAG_
COPY scripts /tmp/scripts
COPY golang /tmp/golang
COPY node /tmp/node
COPY protobuf-3.1.0 /tmp/protobuf-3.1.0
COPY gradle/gradle-2.12-bin.zip /tmp/gradle-2.12-bin.zip
RUN cd /tmp/scripts && \
    common/packages.sh && \
    common/setup.sh && \
    docker/fixup.sh && \
    common/cleanup.sh && \
    rm -rf /tmp/scripts
ENV GOPATH=/opt/gopath
ENV GOROOT=/opt/go
ENV PATH=$PATH:$GOROOT/bin:$GOPATH/bin
